- id: '1626717008773'
  alias: Notifica quando não tem ninguém de casa
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.telefone_matheus
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - group.todas_as_luzes
  initial_state: true
  mode: single
