- platform: smartir
  name: Ar condicionado
  unique_id: ar_condicionado
  device_code: 3001
  controller_data: remote.rm3_remote_quarto
  #temperature_sensor: sensor.temperature
  #humidity_sensor: sensor.humidity
  #power_sensor: binary_sensor.ac_power
