# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

light: !include lights.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
climate: !include climates.yaml
frontend:
  themes: !include_dir_merge_named themes


smartir:
  update_branch: rc

