- platform: switch
  name: "Luz Escritorio"
  entity_id: switch.interruptor_escritorio_l1
- platform: switch
  name: "Luz Corredor"
  entity_id: switch.interruptor_corredor_left
- platform: switch
  name: "Luz Quarto"
  entity_id: switch.interruptor_quarto_left
- platform: switch
  name: "Luz Closet"
  entity_id: switch.interruptor_quarto_center
- platform: switch
  name: "Luz Entrada"
  entity_id: switch.interruptor_entrada_l1
- platform: switch
  name: "Luz Rua"
  entity_id: switch.interruptor_entrada_l4
- platform: switch
  name: "Luz Churrasqueira"
  entity_id: switch.interruptor_entrada_l3
- platform: switch
  name: "Luz Cozinha"
  entity_id: switch.interruptor_cozinha_l1
- platform: switch
  name: "Luz Sala"
  entity_id: switch.interruptor_sala_left
- platform: switch
  name: "Luz Banheiro Suite"
  entity_id: switch.interruptor_banheiro_suite_left
- platform: switch
  name: "Luz Banheiro Visita"
  entity_id: switch.interruptor_banheiro_visita_left
